# Generated by Django 3.1.6 on 2021-02-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='border',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='font',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='image_back',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='image_front',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='message',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
