# Generated by Django 3.1.6 on 2021-02-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210204_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='border_type',
            field=models.CharField(default='solid', max_length=500),
        ),
        migrations.AddField(
            model_name='card',
            name='font_color',
            field=models.CharField(default='white', max_length=500),
        ),
        migrations.AddField(
            model_name='card',
            name='justify',
            field=models.CharField(default='flex-start', max_length=500),
        ),
    ]
