# Generated by Django 3.1.6 on 2021-02-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_card_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='created_date',
            new_name='updated_date',
        ),
    ]
